### ISSUE TITLE
idk how to setup the mod in 1.18.1

### ISSUE THREAD

**Issue by PiercerSG** [HotLava03/chat-utils#4]
Can Someone Help Me Setup The Mod 
Discord:
AlbertGonzaga#3726

**Comment by PiercerSG** [comment]
i really want it right now please help me

**Comment by RealY700** [comment]
You might not remember asking this but I will answer anyways for other people to use

run the following commands in a console
clone the repository:
`git clone https://github.com/HotLava03/chat-utils.git`
or just download the zip and unzip it from this page.

go to the new folder:
`cd chat-utils` (or whatever you called it)

build the mod:
`gradlew build`

after that finishes, you should see the compiled jar in
`chat-utils/build/libs/chat-util-1.5.2.jar`

the steps above worked for me and should hopefully work for you too :)
if this does not work, I'm sorry, I do not have much experience with java or gradle, and cannot help you (I could try though)

**Comment by RealY700** [comment]
if you have a java IDE, like intellij idea, it might be best if you build from there instead of running `gradlew build`, since it can fix gradle issues like ` General error during conversion: Unsupported class file major version 61`, which I got when using the command.

**Comment by HotLava03** [comment]
Sorry for not replying to this earlier and not publishing 1.18's jar. It's now published on [this](https://github.com/HotLava03/chat-utils/releases/tag/1.5.3) link. 

Ps: The gradle task for building Fabric mod jars isn't `build`, but `remapJar`.
